In [ ]:

import numpy as np
import pandas as pd

In [ ]:
credits = pd.read_csv(r"C:\Users\LENOVO\OneDrive\Desktop\data science\tmdb_5000_credits.csv\tmdb_5000_credits.csv")
movies = pd.read_csv(r"C:\Users\LENOVO\OneDrive\Desktop\data science\tmdb_5000_movies.csv\tmdb_5000_movies.csv")

In [ ]:
movies.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [ ]:
credits.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [1]:
credits.head(1)[crew].values

AttributeError: '_Printer' object has no attribute 'head'